booking/urls.py
from django.urls import path 
from booking import views 

app_name = "booking"

urlpatterns = [
    path("check_room_availability/", views.check_room_availability, name="check_room_availability"),
    path("delete_session/", views.delete_session, name="delete_session"),
    path("booking_data/<slug:slug>/", views.booking_data, name="booking_data"),

    # Ajax
    path("add_to_selection/", views.add_to_selection, name="add_to_selection"),
    path("delete_selection/", views.delete_selection, name="delete_selection"),
    
]

hms_prj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', admin.site.urls),

    # Apps Routes
    # path("booking/", include("booking.urls")),
    # path("user/", include("userauths.urls")),
    # path("dashboard/", include("user_dashboard.urls")),

    # Ckeditor
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')), 
    path('i18n/', include('django.conf.urls.i18n')),

]

urlpatterns += i18n_patterns(
    path("", include("hotel.urls")),
    path("booking/", include("booking.urls")),
    path("user/", include("userauths.urls")),
    path("dashboard/", include("user_dashboard.urls")),

)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hotel/urls.py
from django.urls import path 
from hotel import views 

app_name = "hotel"

urlpatterns = [
    path("", views.index, name="index"),
    path("detail/<slug:slug>/", views.hotel_detail, name="detail"),
    path("detail/<slug:slug>/room-type/<slug:rt_slug>/", views.room_type_detail, name="room_type_detail"),
    path("selected_rooms/", views.selected_rooms, name="selected_rooms"),
    path("checkout/<booking_id>/", views.checkout, name="checkout"),
    path("invoice/<booking_id>/", views.invoice, name="invoice"),
    path("update_room_status/", views.update_room_status, name="update_room_status"),
    
    # Payment API
    path('api/checkout-session/<booking_id>/', views.create_checkout_session, name='api_checkout_session'),
    path('success/<booking_id>/', views.payment_success, name='success'),
    path('failed/<booking_id>/', views.payment_failed, name='failed'),
]

hotel/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.utils import timezone
from django.conf import settings
from django.urls import reverse
from django.template.loader import render_to_string
from django.core.mail import EmailMultiAlternatives



from hotel.models import Coupon, CouponUsers, Hotel, Room, Booking, RoomServices, HotelGallery, HotelFeatures, RoomType, RoomTypeGallery, Notification, Bookmark, Review

from datetime import datetime
from decimal import Decimal
import stripe
import json


def index(request):
    hotel = Hotel.objects.filter(status="Live")
    context = {
        "hotel":hotel
    }
    return render(request, "hotel/index.html", context)


def hotel_detail(request, slug):
    hotel = Hotel.objects.get(status="Live", slug=slug)
    room_type_images = RoomTypeGallery.objects.filter(hotel=hotel)
    try:
        reviews = Review.objects.filter(user=request.user, hotel=hotel)
    except:
        reviews = None
    all_reviews = Review.objects.filter(hotel=hotel, active=True)
    
    if request.user.is_authenticated:
        bookmark = Bookmark.objects.filter(user=request.user, hotel=hotel)
    else:
        bookmark = None
    context = {
        "hotel":hotel,
        "bookmark":bookmark,
        "reviews":reviews,
        "all_reviews":all_reviews,
        "room_type_images":room_type_images,
    }
    return render(request, "hotel/hotel_detail.html", context)


def room_type_detail(request, slug, rt_slug):
    hotel = Hotel.objects.get(status="Live", slug=slug)
    room_type = RoomType.objects.get(hotel=hotel, slug=rt_slug)
    rooms = Room.objects.filter(room_type=room_type, is_available=True)

    id = request.GET.get("hotel-id")
    checkin = request.GET.get("checkin")
    checkout = request.GET.get("checkout")
    adult = request.GET.get("adult")
    children = request.GET.get("children")
    room_type_ = request.GET.get("room-type")

    print("checkin ======", checkin)

    if not all([checkin, checkout]):
        messages.warning(request, "Please enter your booking data to check availability.")
        return redirect("booking:booking_data", hotel.slug)

    context = {
        "hotel":hotel,
        "room_type":room_type,
        "rooms":rooms,
        "id":id,
        "checkin":checkin,
        "checkout":checkout,
        "adult":adult,
        "children":children,
        "room_type_":room_type_,
    }
    return render(request, "hotel/room_type_detail.html", context)



def selected_rooms(request):
    # request.session.pop('selection_data_obj', None)

    total = 0
    room_count = 0
    total_days = 0
    adult = 0 
    children = 0 
    checkin = "0" 
    checkout = "" 
    children = 0 
    
    if 'selection_data_obj' in request.session:

        if request.method == "POST":
            for h_id, item in request.session['selection_data_obj'].items():
                
                id = int(item['hotel_id'])
                hotel_id = int(item['hotel_id'])

                checkin = item["checkin"]
                checkout = item["checkout"]
                adult = int(item["adult"])
                children = int(item["children"])
                room_type_ = item["room_type"]
                room_id = int(item["room_id"])
                
                user = request.user
                hotel = Hotel.objects.get(id=id)
                room = Room.objects.get(id=room_id)
                room_type = RoomType.objects.get(id=room_type_)

                

                
            date_format = "%Y-%m-%d"
            checkin_date = datetime.strptime(checkin, date_format)
            checout_date = datetime.strptime(checkout, date_format)
            time_difference = checout_date - checkin_date
            total_days = time_difference.days

            full_name = request.POST.get("full_name")
            email = request.POST.get("email")
            phone = request.POST.get("phone")

            booking = Booking.objects.create(
                hotel=hotel,
                room_type=room_type,
                check_in_date=checkin,
                check_out_date=checkout,
                total_days=total_days,
                num_adults=adult,
                num_children=children,
                full_name=full_name,
                email=email,
                phone=phone
            )

            if request.user.is_authenticated:
                booking.user = request.user
                booking.save()
            else:
                booking.user = None
                booking.save()


            for h_id, item in request.session['selection_data_obj'].items():
                room_id = int(item["room_id"])
                room = Room.objects.get(id=room_id)
                booking.room.add(room)

                room_count += 1
                days = booking.total_days
                price = booking.room_type.price

                room_price = price * room_count
                total = room_price * days

                # print("room_price ==",room_price)
                # print("total ==",total)
            
            booking.total += float(total)
            booking.before_discount += float(total)
            booking.save()

            messages.success(request, "Checkout Now!")
            return redirect("hotel:checkout", booking.booking_id)

        hotel = None

        for h_id, item in request.session['selection_data_obj'].items():
                
            id = int(item['hotel_id'])
            hotel_id = int(item['hotel_id'])

            checkin = item["checkin"]
            checkout = item["checkout"]
            adult = int(item["adult"])
            children = int(item["children"])
            room_type_ = item["room_type"]
            room_id = int(item["room_id"])
            
            room_type = RoomType.objects.get(id=room_type_)

            date_format = "%Y-%m-%d"
            checkin_date = datetime.strptime(checkin, date_format)
            checout_date = datetime.strptime(checkout, date_format)
            time_difference = checout_date - checkin_date
            total_days = time_difference.days

            room_count += 1
            days = total_days
            price = room_type.price

            room_price = price * room_count
            total = room_price * days
            
            hotel = Hotel.objects.get(id=id)

        print("hotel ===", hotel)
        context = {
            "data":request.session['selection_data_obj'], 
            "total_selected_items": len(request.session['selection_data_obj']),
            "total":total,
            "total_days":total_days,
            "adult":adult,
            "children":children,   
            "checkin":checkin,   
            "checkout":checkout,   
            "hotel":hotel,   
        }

        return render(request, "hotel/selected_rooms.html", context)
    else:
        messages.warning(request, "You don't have any room selections yet!")
        return redirect("/")

def checkout(request, booking_id):
    booking = Booking.objects.get(booking_id=booking_id)

    if booking.payment_status == "paid":
        messages.success(request, "This order has been paid for!")
        return redirect("/")
    else:
        booking.payment_status = "processing"
        booking.save()


    # Coupon
    now = timezone.now()
    if request.method == "POST":
        # Get code entered in the input field
        code = request.POST.get('code')
        print("code ======", code)
        try:
            coupon = Coupon.objects.get(code__iexact=code,valid_from__lte=now,valid_to__gte=now,active=True)
            if coupon in booking.coupons.all():
                messages.warning(request, "Coupon Already Activated")
                return redirect("hotel:checkout", booking.booking_id)
            else:
                CouponUsers.objects.create(
                    booking=booking,
                    coupon=coupon,
                    full_name=booking.full_name,
                    email=booking.email,
                    mobile=booking.phone,
                )

                if coupon.type == "Percentage":
                    discount = booking.total * coupon.discount / 100
                else:
                    discount = coupon.discount

                booking.coupons.add(coupon)
                booking.total -= discount
                booking.saved += discount
                booking.save()

                
                messages.success(request, "Coupon Found and Activated")
                return redirect("hotel:checkout", booking.booking_id)
        except Coupon.DoesNotExist:
            messages.error(request, "Coupon Not Found")
            return redirect("hotel:checkout", booking.booking_id)
    
    context = {
        "booking":booking,  
        "stripe_publishable_key":settings.STRIPE_PUBLIC_KEY,
        "flutter_publick_key":settings.FLUTTERWAVE_PUBLIC,
        "website_address":settings.WEBSITE_ADDRESS,
    }
    return render(request, "hotel/checkout.html", context)


@csrf_exempt
def create_checkout_session(request, booking_id):
    request_data = json.loads(request.body)
    booking = get_object_or_404(Booking, booking_id=booking_id)

    stripe.api_key = settings.STRIPE_PRIVATE_KEY
    checkout_session = stripe.checkout.Session.create(
        customer_email = booking.email,
        payment_method_types=['card'],
        line_items=[
            {
                'price_data': {
                    'currency': 'usd',
                    'product_data': {
                    'name': booking.full_name,
                    },
                    'unit_amount': int(booking.total * 100),
                },
                'quantity': 1,
            }
        ],
        mode='payment',

templates/hotel/checkout.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}
{% load i18n %}
<div id="main_wrapper">
  
  <div id="titlebar" class="gradient">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2>{% trans "All Room Selections" %}</h2>
          <nav id="breadcrumbs">
            <ul>
              <li><a>{% trans "Home" %}</a></li>
              <li><a>{% trans "Hotel" %}</a></li>
              <li><a>{% trans "Rooms" %}</a></li>
              <li>{% trans "My selected rooms" %}</li>
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </div>
  
  <div class="container margin-bottom-75">
    <div class="row">
      <div class="col-lg-8 col-md-8 utf_listing_payment_section">
	    <div class="notification warning closeable">
			<p><span>{% trans "NOTE!" %}</span> {% trans "Review your order before payment." %}</p>
			<a class="close" href="#"></a> 
		  </div>
        <div class="utf_booking_listing_section_form margin-bottom-40">
            <h3><i class="fas fa-bed"></i> {% trans "Selected Rooms" %}</h3>
            <div class="utf_listing_section">
                    <div class="utf_pricing_list_section">
                        <ul>
                            {% for r in booking.room.all %}
                                <li>
                                    <h5>{% trans "Room" %}: {{r.room_type.type}} </h5>
                                    <p><strong>{% trans "Beds" %} :</strong> {{r.number_of_beds}}  </p>
                                    <span>${{r.room_type.price}} </span>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
            </div>
        </div>
            
        <div class="utf_booking_listing_section_form margin-bottom-40">
		  <h3><i class="fas fa-user"></i> {% trans "Billing Information" %}</h3>
			<div class="row">
			  <div class="col-md-12">
				<label>{% trans "First Name" %}</label>
				<input name="full_name" type="text" value="{{booking.full_name}}" readonly placeholder="First Name">
			  </div>
			  <div class="col-md-6">
				<div class="medium-icons">
				  <label>{% trans "E-Mail" %}</label>
				  <input name="email" id="email" type="text" value="{{booking.email}}" readonly placeholder="Email">
				</div>
			  </div>
			  <div class="col-md-6">
				<div class="medium-icons">
				  <label>{% trans "Phone" %}</label>
				  <input name="phone" type="text" value="{{booking.phone}}" readonly >
				</div>
			  </div>
              <div class="col-lg-12">
			  </div>
			</div>
		</div>

		
	  </div>
      <div class="col-lg-4 col-md-4 margin-top-0 utf_listing_payment_section">
        <div class="utf_booking_listing_item_container compact utf_order_summary_widget_section">
          <div class="listing-item"> <img src="{{booking.hotel.image.url}}" alt="">
            <div class="utf_listing_item_content">              
              <h3>{{booking.hotel.name}}</h3>
              <span><i class="fa fa-map-marker"></i> The Ritz-Carlton, Hong Kong</span>
						<span><i class="fa fa-phone"></i> (+15) 124-796-3633</span>											
			  <div class="utf_star_rating_section" data-rating="4.5">
				<div class="utf_counter_star_rating">(18) Reviews</div>
			  </div>
			</div>
          </div>
        </div>
        <div class="boxed-widget opening-hours summary margin-top-0">
          <h3><i class="fa fa-calendar-check-o"></i> {% trans "Booking Summary" %}</h3>
          <ul>
            <li>{% trans "Check-in" %} <span>{{booking.check_in_date}}</span></li>
			      <li>{% trans "Check-out" %} <span>{{booking.check_out_date}}</span></li>            
            <li>{% trans "Adults" %} <span>{{ booking.num_adults }} {% trans "Adults" %}</span></li>
            <li>{% trans "Children" %} <span>{{ booking.num_children }} {% trans "Children" %}</span></li>
			      <li>{% trans "V.A.T" %} <span>$0.00</span></li>
            
            {% if booking.saved != 0.00 %}
			      <li>{% trans "Discount" %}<span>-${{booking.saved}}</span></li>
            {% endif %}

            <li class="total-costs">
              <form action="" method="POST">
                {% csrf_token %}
                <div class="col-md-8">
                  <input id="couponCode" name="code" placeholder="Have a coupon enter here..." required="" type="text">
                </div>
                <div class="col-md-4">
                  <input type="submit" class="coupon_code" value="Apply">	
                </div>
              </form>
              <div class="clearfix"></div>
            </li>
            <li class="total-costs">{% trans "Total Cost" %} <span>${{booking.total}}</span></li>
          </ul>
          <form method="POST" action="https://checkout.flutterwave.com/v3/hosted/pay">
               <input type="hidden" name="public_key" value="FLWPUBK_TEST-a2c377d3cf56b37b9e660f85e26d2f8f-X" />
               <input type="hidden" name="customer[email]" value="{{booking.email}}" />
               <input type="hidden" name="customer[name]" value="{{booking.full_name}}" />
               <input type="hidden" name="tx_ref" value="ID-{{booking.booking_id}}" />
               <input type="hidden" name="amount" value="{{booking.total}}" />
               <input type="hidden" name="currency" value="USD" />
               <input type="hidden" name="meta[token]" value="54" />
               <input type="hidden" name="redirect_url" value="{{website_address}}/success/{{booking.booking_id}}/?success_id={{booking.success_id}}&booking_total={{booking.total}}" />
               
               <button id="flutter-btn" class="button utf_booking_confirmation_button margin-top-20 w-100 " style="background-color: orange; color: rgb(37, 28, 3);">{% trans "Pay with Flutterwave" %} <img src="https://asset.brandfetch.io/iddYbQIdlK/idmlgmHt_3.png" style="width: 40px;" alt=""></button> 		
          </form>
          <button id="checkout-button" class="button utf_booking_confirmation_button margin-top-10 margin-bottom-10 w-100">{% trans "Pay with Stripe" %} <i class="fas fa-credit-card"></i></button> 		
          <div id="paypal-button-container"></div>
        </div>
      </div>
    </div>
  </div>
</div>

<script src="https://www.paypal.com/sdk/js?client-id=test&currency=USD"></script>
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://js.stripe.com/v3/"></script>

<script type="text/javascript">



    // Create an instance of the Stripe object with your publishable API key
    var stripe = Stripe('{{ stripe_publishable_key }}');
    var checkoutButton = document.getElementById('checkout-button');

    checkoutButton.addEventListener('click', function () {

        var email = document.getElementById('email').value;
        if (email.length == 0) {
            alert("Please enter your email address.");
            return;
        }

        checkoutButton.innerHTML = "Starting..."
        
        fetch("{% url 'hotel:api_checkout_session' booking_id=booking.booking_id %}", {
            method: 'POST',
            body: JSON.stringify(
                { email: email }
            )
        }).then(function (response) {
                return response.json();
            })
            .then(function (session) {
                return stripe.redirectToCheckout({ sessionId: session.sessionId });
            })
            .then(function (result) {
                if (result.error) {
                    alert(result.error.message);
                }
            })
            .catch(function (error) {
                console.error('Error:', error);
            });
    });
</script>


<script>
   booking_id = "{{booking.booking_id}}"
   booking_total = "{{booking.total}}"
   success_id = "{{booking.success_id}}"
   id = "{{booking.id}}"

   paypal.Buttons({

      createOrder: function(data, actions) {
         return actions.order.create({
            purchase_units: [{
               amount: {
                  value: booking_total
               }
            }]
         })
      },

       onApprove: function(data, actions) {
           return actions.order.capture().then(function(Details){
              window.location.href = "/success/"+ booking_id +"/?PayerID="+ id +"&success_id=" + success_id + "&booking_total=" + booking_total + "/" ; 
           })
       }

   }).render('#paypal-button-container');
</script>

<script>
  let flutter_btn = document.getElementById("flutter-btn")
  flutter_btn.addEventListener("click", function(){
    flutter_btn.innerHTML = "Starting..."
  })
</script>
  
{% endblock content %}

templates/hotel/payment_success.html
{% extends 'partials/base.html' %}
{% load static %}
{% load i18n %}
{% block content %}
  
  <div class="not_found_block">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <section id="not-found" class="center">
            <h2 class="margin-bottom-10"><i class="fas fa-check-circle" style="color: green;"></i></h2>
            <p style="margin-top: 10px; color: black;"><b>Checkout & Payment Successfull!</b></p>
            <div class="utf_error_description_part utf_ferror_description">  
                <span class="f-primary animated v fadeInRight">We have sent your booking summary to <b>{{ booking.email }}. Thank you.</b></span> 
            </div>
            <a href="{% url 'hotel:invoice' booking.booking_id %}" class="button margin-top-20">Visit Dashboard</a>
            <a href="{% url 'hotel:invoice' booking.booking_id %}" target="_blank" class="button margin-top-20">View Invoice 🧾</a>
            <div class="row">
              <div class="col-lg-6 col-lg-offset-3">
                <div class="gray-style margin-top-50 margin-bottom-10">
                </div>
              </div>
            </div>
          </section>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

templates/hotel/room_type_detail.html
{% extends 'partials/base.html' %}
{% load static %}
{% load i18n %}
{% block content %}
  
  <div id="titlebar" class="gradient">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2>{{room_type.type}} {% trans "Room" %}</h2>
          <nav id="breadcrumbs">
            <ul>
              <li><p>{{rooms.count}} {% trans "Available Rooms" %}</p></li>
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </div>

  
  <section class="fullwidth_block margin-top-0 padding-top-0 padding-bottom-50" data-background-color="#fff"> 
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h3 class="headline_part centered margin-bottom-20">{% trans "All Available Rooms" %}<span>{% blocktrans with room_type=room_type.type rooms_count=rooms.count %}The {{ room_type }} room has {{ rooms_count }} available room(s){% endblocktrans %}</span></h3>
        </div>
      </div>
      <div class="row">  
        <div class="col-lg-8 "> 
          
          {% for r in rooms %}
              <div class="plan featured col-md-4 col-sm-6 col-xs-12">
              <div class="utf_price_plan">
                  <h3>{% trans "Room No." %} {{ r.room_number }}</h3>
                  <span class="value">${{r.room_type.price}}<span>{% trans "/Per Night" %}</span></span> 
              </div>
              <div class="utf_price_plan_features">
                  <ul>
                  <li>{% trans "Beds" %}: {{r.room_type.number_of_beds}} </li>
                  <li>{% trans "Room Capacity" %}: {{r.room_type.room_capacity}}</li>
                  </ul>
                  <input type="hidden" class="room_id_{{r.id}}" value="{{r.id}}" id="room_id">
                  <input type="hidden" class="room_number_{{r.id}}" value="{{r.room_number}}" id="room_number">
                  <button class="button border add-to-selection" data-index="{{r.id}}"><i class="fas fa-shopping-cart"></i> {% trans "Add To Selection" %}</button> 
              </div>
              </div>
          {% endfor %}
          <input type="hidden" value="{{hotel.id}}" id="id">
          <input type="hidden" value="{{hotel.name}}" id="hotel_name">
          <input type="hidden" value="{{room_type.type}}" id="room_name">
          <input type="hidden" value="{{room_type.price}}" id="room_price">
          <input type="hidden" value="{{room_type.number_of_beds}}" id="number_of_beds">
          <input type="hidden" value="{{room_type.id}}" id="room_type">
          <input type="hidden" value="{{checkin}}" id="checkin">
          <input type="hidden" value="{{checkout}}" id="checkout">
          <input type="hidden" value="{{adult}}" id="adult">
          <input type="hidden" value="{{children}}" id="children">

          
        </div>  
        <div class="col-lg-4">
            <div class=" booking_widget_box" style="border: 1px dashed rgba(42, 1, 119, 0.61); padding: 14px; border-radius: 10px;">
              <h3><i class="fa fa-calendar"></i> {% trans "Booking" %}</h3>
              <form class="row with-forms margin-top-0" method="POST" action="{% url 'booking:check_room_availability' %}">
                  {% csrf_token %}
                  <input type="hidden" value="{{hotel.id}}" name="hotel-id" id="">
                  <div class="col-lg-12 col-md-12 select_date_box">
                      <label for="">{% trans "Check-in Date" %}</label>
                      <input type="date" id="date-picker" value="{{checkin}}" name="checkin" placeholder="Select Date">
                  </div>
                  <div class="col-lg-12 col-md-12 select_date_box">
                      <label for="">{% trans "Check-out Date" %}</label>
                      <input type="date" class="checkout_date" name="checkout" value="{{checkout}}"  placeholder="Select Date">
                  </div>
                  <div class="with-forms">
                      <div class="col-lg-12 col-md-12">
                          <a href="#">{% trans "Guests" %} <span class="qtyTotal" name="qtyTotal">1</span></a>
                          <div class="panel-dropdown-content">
                              <div class="qtyButtons">
                                  <div class="qtyTitle">{% trans "Adults" %}</div>
                                  <input type="text" name="adult" {% if adult == None %}value="1"{% else %}value="{{adult}}"{% endif %}>
                              </div>
                              <div class="qtyButtons">
                                  <div class="qtyTitle">{% trans "Childrens" %}</div>
                                  <input type="text" name="children" {% if children == None %}value="1"{% else %}value="{{children}}"{% endif %}>
                              </div>
                          </div>
                      </div>
                  </div>

                  <div class="with-forms margin-top-30">
                      <div class="col-lg-12 col-md-12 ">
                          <a href="#">{% trans "Select Room Type" %}</a>
                          <select name="room-type" class="utf_chosen_select_single" required>
                              <!-- <option value="{{room_type|lower}}">{{room_type}}</option> -->
                              <option value="{{room_type|lower}}">{{room_type}}</option>

                              {% for r in hotel.hotel_room_types %}
                                  <option value="{{r.slug}}">{{r.type}}</option>
                              {% endfor %}
                            </select>
                      </div>
                  </div>
                
                  <button type="submit" class="utf_progress_button button fullwidth_block margin-top-5">{% trans "Check Availability" %}</button>
              </form>
              <button class="like-button add_to_wishlist"><span class="like-icon"></span> {% trans "Add to Wishlist" %}</button>
              <div class="clearfix"></div>
            </div>
        </div>      
              
      </div>      
    </div>    
  </section>

  <script>
    $(document).ready(function(){
        
        var dateInput = $('#checkout_date');

        dateInput.on('change', function() {
            var selectedDate = dateInput.val();
            console.log('Selected date:', selectedDate);
        });
    })
  </script>
  
{% endblock content %}